// <auto-generated />
namespace WebsiteBanGiayDep23.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update01));
        
        string IMigrationMetadata.Id
        {
            get { return "202308160618386_Update01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
